# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Test Build

on:
  push:
  workflow_dispatch:

jobs:
  maven_build:
    name: Maven-Build (Linux)
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      activemq:
        image: quay.io/artemiscloud/activemq-artemis-broker:latest
        ports:
          - 61616:61616
        env:
          AMQ_USER: admin
          AMQ_PASSWORD: admin

      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: postgres

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build with Maven
        run: mvn -B install --file pom.xml

      # Sofern das Projekt mit Teamscale analysiert werden soll, bitte einkommenteieren
      # WICHTIG: Zuvor muss das Projekt in Teamscale erstellt werden.
      #- name: Teamscale Upload
      #  uses: cqse/teamscale-upload-action@v2.6.0
      #  with:
      #    server: 'https://dillinger.teamscale.io'
      #    project: 'jexxatemplate'
      #    user: 'upload'
      #    partition: 'Jacoco Reports'
      #    accesskey: ${{ secrets.TEAMSCALE_UPLOAD }}
      #    format: 'JACOCO'
      #    branch-and-timestamp: 'main:HEAD'
      #    message: 'Hochladen von test reports.'
      #    files: 'target/site/jacoco/jacoco.xml target/site/jacoco-aggregate/jacoco.xml target/site/jacoco-it/jacoco.xml'